version: '3.7'

services:
  frontend-prod:
    container_name: o2n-front-prod
    volumes:
      - '/frontend/app'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  backend-prod:
    container_name: o2n-backend-prod
    volumes: 
      - ./backend/db.json:/data/db.json
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always