version: '3.7'

services:
  frontend-prod:
    container_name: o2n-front-prod
    volumes:
      - '/frontend/app'
      - '/frontend/node_modules'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  backend-prod:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 8000 -w db.json
    volumes:
      - './backend:/data'
    ports:
      - "8000:8000"
    restart: always